### ISSUE TITLE
iTunes refuses to work

### ISSUE THREAD

**Issue by ghost** [theonlylawislove/iTunesMobileDevice-Hook#1]
Severity    Code    Description Project File    Line
Error   LNK1104 cannot open file 'C:\Program Files\Common Files\Apple\Mobile Device Support\iTunesMobileDevice.dll' iTunesMobileDevice  D:\FileLab\WinBuild\iTunesMobileDevice-Hook-master\iTunesMobileDevice-Hook-master\iTunesMobileDevice\LINK   1

**Comment by pauldotknopf** [comment]
You have to run [this](https://github.com/theonlylawislove/iTunesMobileDevice-Hook/blob/master/GenerateStubs/Program.cs) task to generate a header file to include in the project. Be sure to uncomment any methods you wish to inspect.

**Comment by exaphaser** [comment]
I'm not sure I understand...

**Comment by ghost** [comment]
I just built the library; how do I inspect output?

**Comment by pauldotknopf** [comment]
You have to attach a debugger (using Visual Studio) to the process that loaded your new DLL. Then, just set a breakpoint.

**Comment by ghost** [comment]
Thanks a lot! Works perfectly. However, your parameters for AMDeviceGetWirelessBuddy flags are wrong; I might send a pull request.
Additionally, iTunes refuses to work while I have this library hooking the original?

**Comment by pauldotknopf** [comment]
> However, your parameters for AMDeviceGetWirelessBuddy flags are wrong; I might send a pull request.

If you know the correct flags, or even better, the full struct definitions for all the `void*` pointers, that would be awesome. There is NO documentation for those, and I would really like to see how iTunes does it's thing.

> Additionally, iTunes refuses to work while I have this library hooking the original?

What do you mean by refuse? Have you placed your newly built dll into the directory where iTunes loads it? Remember, you have to rename the real itunes dll to iTunesMobileDeviceReal.dll, while your intermediate spy dll replaces the original iTunesMobileDevice.dll.

**Comment by ghost** [comment]
1. Yes, all other programs work except iTunes, which complains that the library could not be found.
   I agree, I would really like some documentation, but unfortunately that is not available, as it is _Apple_ that created this library.
2. I was able to find some more information from other open source projects attempting to wrap iTunesMobileDevice, and I myself am working on a unified .NET library that implements 4 interfaces to access iDevices, 3 through iTunesMobileDevice, and 1 through the amazing LibiMobileDevice library. It is going to be open source, but it is still in heavy development and as it was thrown together in a short amount of time, I have not had time to do extensive testing.

Edit x1:
Wrapper Library published!
This contains some more method signatures in the MobileDevice.cs file, the direct iTunesMobileDevice wrapper. Additionally, it contains the method signatures for LibiMobileDevice.
[MK.MobileDevice](https://github.com/exaphaser/MK.MobileDevice)

Edit x2:
I added a wiki to the project so new users would know what to do.

**Comment by ghost** [comment]
I can confirm that iTunes still is not working with the hook.

**Comment by pauldotknopf** [comment]
Are you getting an actual runtime error? Or, a generic error that iTunes itself produces? I'm willing to be that iTunes does some kind of checksum validation of the file to make sure it isn't a proxy.

Fuck Apple...

**Comment by ghost** [comment]
That's what I was thinking... it's not a runtime error; iTunes complains that it cannot find the library, while every other iTunes alternative works just fine. I think it's a checksum, and I highly doubt that's patchable.

Agreed. I hate Apple.
